insert into response_value(id,response) values(0,'It is certain.');
insert into response_value(id,response) values(1,'It is decidedly so.');
insert into response_value(id,response) values(2,'Without a doubt.');
insert into response_value(id,response) values(3,'Yes - definitely.');
insert into response_value(id,response) values(4,'You may rely on it.');
insert into response_value(id,response) values(5,'As I see it, yes.');
insert into response_value(id,response) values(6,'Most likely.');
insert into response_value(id,response) values(7,'Outlook good.');
insert into response_value(id,response) values(8,'Yes.');
insert into response_value(id,response) values(9,'Signs point to yes.');
insert into response_value(id,response) values(10,'Reply hazy, try again.');
insert into response_value(id,response) values(11,'Ask again later.');
insert into response_value(id,response) values(12,'Better not tell you now.');
insert into response_value(id,response) values(13,'Cannot predict now.');
insert into response_value(id,response) values(14,'Concentrate and ask again.');
insert into response_value(id,response) values(15,'Dont count on it.');
insert into response_value(id,response) values(16,'My reply is no.');
insert into response_value(id,response) values(17,'My sources say no.');
insert into response_value(id,response) values(18,'Outlook not so good.');
insert into response_value(id,response) values(19,'Very doubtful.');